wandb: Currently logged in as: grassknoted (serrelab). Use `wandb login --relogin` to force relogin
wandb: Appending key for api.wandb.ai to your netrc file: /users/schen336/.netrc
wandb: Tracking run with wandb version 0.16.3
wandb: Run data is saved locally in /oscar/home/schen336/Desktop/proj-brainstorm2024/wandb/run-20240304_205455-0bylgcje
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run zany-night-173
wandb: ‚≠êÔ∏è View project at https://wandb.ai/serrelab/prj_brainstorm
wandb: üöÄ View run at https://wandb.ai/serrelab/prj_brainstorm/runs/0bylgcje
/users/schen336/.local/lib/python3.9/site-packages/torch/utils/data/dataloader.py:557: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 1, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
config.json:   0%|          | 0.00/725 [00:00<?, ?B/s]config.json: 100%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà| 725/725 [00:00<00:00, 245kB/s]
pytorch_model.bin:   0%|          | 0.00/377M [00:00<?, ?B/s]pytorch_model.bin:   3%|‚ñé         | 10.5M/377M [00:00<00:05, 70.1MB/s]pytorch_model.bin:   6%|‚ñå         | 21.0M/377M [00:00<00:04, 78.9MB/s]pytorch_model.bin:   8%|‚ñä         | 31.5M/377M [00:00<00:05, 61.0MB/s]pytorch_model.bin:  14%|‚ñà‚ñç        | 52.4M/377M [00:00<00:04, 66.2MB/s]pytorch_model.bin:  17%|‚ñà‚ñã        | 62.9M/377M [00:00<00:04, 72.3MB/s]pytorch_model.bin:  19%|‚ñà‚ñâ        | 73.4M/377M [00:01<00:03, 77.6MB/s]pytorch_model.bin:  22%|‚ñà‚ñà‚ñè       | 83.9M/377M [00:01<00:03, 73.9MB/s]pytorch_model.bin:  28%|‚ñà‚ñà‚ñä       | 105M/377M [00:01<00:04, 55.9MB/s] pytorch_model.bin:  31%|‚ñà‚ñà‚ñà       | 115M/377M [00:01<00:04, 63.0MB/s]pytorch_model.bin:  36%|‚ñà‚ñà‚ñà‚ñå      | 136M/377M [00:01<00:03, 74.6MB/s]pytorch_model.bin:  42%|‚ñà‚ñà‚ñà‚ñà‚ñè     | 157M/377M [00:02<00:02, 82.4MB/s]pytorch_model.bin:  45%|‚ñà‚ñà‚ñà‚ñà‚ñç     | 168M/377M [00:02<00:02, 74.9MB/s]pytorch_model.bin:  50%|‚ñà‚ñà‚ñà‚ñà‚ñà     | 189M/377M [00:02<00:02, 84.9MB/s]pytorch_model.bin:  53%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñé    | 199M/377M [00:02<00:02, 88.3MB/s]pytorch_model.bin:  56%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñå    | 210M/377M [00:02<00:02, 63.6MB/s]pytorch_model.bin:  58%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñä    | 220M/377M [00:03<00:02, 69.8MB/s]pytorch_model.bin:  64%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñç   | 241M/377M [00:03<00:01, 78.1MB/s]pytorch_model.bin:  70%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñâ   | 262M/377M [00:03<00:01, 83.2MB/s]pytorch_model.bin:  72%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñè  | 273M/377M [00:03<00:01, 84.0MB/s]pytorch_model.bin:  78%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñä  | 294M/377M [00:03<00:00, 86.3MB/s]pytorch_model.bin:  83%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñé | 315M/377M [00:04<00:00, 77.7MB/s]pytorch_model.bin:  89%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñâ | 336M/377M [00:04<00:00, 87.5MB/s]pytorch_model.bin:  92%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñè| 346M/377M [00:04<00:00, 59.8MB/s]pytorch_model.bin:  97%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñã| 367M/377M [00:05<00:00, 55.9MB/s]pytorch_model.bin: 100%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà| 377M/377M [00:05<00:00, 55.0MB/s]pytorch_model.bin: 100%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà| 377M/377M [00:05<00:00, 69.8MB/s]
  0%|          | 0/102 [00:00<?, ?it/s]/users/schen336/.local/lib/python3.9/site-packages/torch/utils/data/dataloader.py:557: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 1, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
  0%|          | 0/102 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/oscar/home/schen336/Desktop/proj-brainstorm2024/main.py", line 136, in <module>
    main(args)
  File "/oscar/home/schen336/Desktop/proj-brainstorm2024/main.py", line 93, in main
    train(video_encoder, seeg_encoder, optimizer, train_loader, device, t)
  File "/oscar/home/schen336/Desktop/proj-brainstorm2024/train/train.py", line 18, in train
    for video, seeg in tqdm(train_loader):
  File "/users/schen336/.local/lib/python3.9/site-packages/tqdm/std.py", line 1182, in __iter__
    for obj in iterable:
  File "/users/schen336/.local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/users/schen336/.local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/users/schen336/.local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/users/schen336/.local/lib/python3.9/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
NameError: Caught NameError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/users/schen336/.local/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/users/schen336/.local/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = self.dataset.__getitems__(possibly_batched_index)
  File "/users/schen336/.local/lib/python3.9/site-packages/torch/utils/data/dataset.py", line 364, in __getitems__
    return [self.dataset[self.indices[idx]] for idx in indices]
  File "/users/schen336/.local/lib/python3.9/site-packages/torch/utils/data/dataset.py", line 364, in <listcomp>
    return [self.dataset[self.indices[idx]] for idx in indices]
  File "/oscar/home/schen336/Desktop/proj-brainstorm2024/dataset/dataset.py", line 45, in __getitem__
    video = self.sample_frames(video)
  File "/oscar/home/schen336/Desktop/proj-brainstorm2024/dataset/dataset.py", line 80, in sample_frames
    max_start_index = video_array.shape[0] - stride * (num_frames - 1)
NameError: name 'num_frames' is not defined

wandb: - 0.004 MB of 0.004 MB uploadedwandb: \ 0.004 MB of 0.004 MB uploadedwandb: | 0.004 MB of 0.004 MB uploadedwandb: / 0.009 MB of 0.009 MB uploadedwandb: üöÄ View run zany-night-173 at: https://wandb.ai/serrelab/prj_brainstorm/runs/0bylgcje
wandb: Ô∏è‚ö° View job at https://wandb.ai/serrelab/prj_brainstorm/jobs/QXJ0aWZhY3RDb2xsZWN0aW9uOjEzNzY5NzI1MQ==/version_details/v22
wandb: Synced 6 W&B file(s), 0 media file(s), 2 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20240304_205455-0bylgcje/logs
